language: node_js
node_js:
- v12
deploy:
  provider: npm
  email: giles.dring@odileeds.org
  api_key:
    secure: duuNF2T7ozcwQzUSJ0+YTSeiAVHXW94r5T3amsTpfMhTGsqtFA9+bJmxFuwVrbu8eHaTgWM0sFMTZ693hLzcP0DMnXmgk6shz3Tz30vOLCFDcIQJvxfZ0tXgYeiJnT1miw305WUF2VCHRQB5iwd165eP206PhQ14vYS0nXhj27mOW6A8Lzhz8jKUVi63awZdpJJ3SPYC9IIw9LlI3KsmO5NaT2d+J6ntyFJjmrzwjoJHtyxQSS9GkcIFp2DVbaMGTjf9H7UbyYx1X+exMvf/jyzYswBVckr10MyZNFwBI7WJoEfrCptNAGKubPyjES8MjoWkiI8o2cuToAK1Am6LMUFz0Qn1Ud1dZ+QlzsFXHexHeJ/HVTSp5gs3sBeBuP5xT721iPWlrT+hqOXE7JlPBJRhCdXIgMEMs1xboXCaun+wVTQaqjAoPKuYz+1sl4wpCgK8ACIKOmf6tQIy7EN+XD1gI3QKgdxoU3bCIzjfEXqABn3i2c8oYOQ0jMZ67n9j6wTX6COav86aJ8aBLhKlgDrrU5Qj9t7KESw1zTEZoLP8tngTjtshjdINwfFhErivLZFr8PS84wVpgdoowz9pauOEHfykNfL2vQOIHaAgexshREtJrx0CHk+G/KAVbHkeGHGc6Dx8hb7nXjD9XRtFY992CttNmgfnR6kxoGOgwTY=
  on:
    tags: true
after_script: cat ./reports/coverage/lcov.info | coveralls
